version: '3'

services:
  frontendreact:
    image: 'node:10-alpine'
    container_name: Frontend-React
    restart: unless-stopped
    working_dir: /myapp/frontend
    volumes:
      - ./frontend:/myapp/frontend
    ports:
      - '3000:3000'
    command: 'yarn start'
